### ISSUE TITLE
How to load the database file from host for Docker installation?

### ISSUE THREAD

**Issue by windware-ono** [ncarlier/feedpushr#49]
I'm trying to run this via docker compose but I'm not sure how I can achieve this to bind mount the database file (and the .htpasswd file) from the host. Otherwise all the data gets wiped after down and up.

**Comment by ncarlier** [comment]
Hi, you can mount a volume on the host. Example:

```yaml
feedpushr:
    image: "ncarlier/feedpushr:latest"
    restart: always
    working_dir: /var/opt/feedpushr
    environment:
      - FP_LOG_LEVEL=info
    volumes:
      - /var/opt/feedpushr:/var/opt/feedpushr
```

Regards


```

**Comment by windware-ono** [comment]
Sorry I was specifying the `FP_DB` environment variable in a wrong format without the `boltdb://` prefix.

Now it's working with a custom path.

```
volumes:
  - /opt/feedpushr/data.db:/data.db
environment:
  - FP_DB=boltdb:///data.db
```

However, `.htpasswd` doesn't seem to work the same way by providing the following with filled in `htpasswd` file but no authentication is asked, but am I doing it wrong?

```
volumes:
  - /opt/feedpushr/htpasswd:/htpasswd
environment:
  - FP_AUTHN=/htpasswd
```

**Comment by ncarlier** [comment]
It should... You can declare only one `volumes` section in a compose file.
To simplify things, I suggest that you simply mount your hosts directory (`opt/feedpushr`) and leave the default configuration :

```yaml
feedpushr:
    image: "ncarlier/feedpushr:latest"
    restart: always
    working_dir: /var/opt/feedpushr
    environment:
      - FP_LOG_LEVEL=debug
    volumes:
      - /opt/feedpushr:/var/opt/feedpushr
```
If you do so, your password file should be located here on your host: `/opt/feedpushr/.htpasswd`
